Traceback (most recent call last):
  File "train.py", line 87, in <module>
    main(config)
  File "train.py", line 65, in main
    trainer.train()
  File "/home/xinyuzhao/faultModel/src/base/base_trainer.py", line 61, in train
    result = self._train_epoch(epoch)
  File "/home/xinyuzhao/faultModel/src/trainer/fault_trainer.py", line 52, in _train_epoch
    origin,injected=FaultInject.weight_inject(self.fault,self.model)
  File "/home/xinyuzhao/faultModel/src/playground/corrupt.py", line 41, in weight_inject
    for fault in faults:
TypeError: 'Fault' object is not iterable

real	3m38.537s
user	5m21.853s
sys	1m47.278s
