Traceback (most recent call last):
  File "train.py", line 89, in <module>
    main(config)
  File "train.py", line 67, in main
    trainer.train()
  File "/home/xinyuzhao/faultModel/src/base/base_trainer.py", line 61, in train
    result = self._train_epoch(epoch)
  File "/home/xinyuzhao/faultModel/src/trainer/fault_trainer.py", line 52, in _train_epoch
    origin,injected=FaultInject.weight_inject(self.fault,self.model)
  File "/home/xinyuzhao/faultModel/src/playground/corrupt.py", line 40, in weight_inject
    FaultInject._weight_inject(faults, model, reset, **kwargs)
  File "/home/xinyuzhao/faultModel/src/playground/corrupt.py", line 66, in _weight_inject
    orig_value, injected_value= FaultInject._tensor_inject(weight,corrupt_idx,corrupt_value)
  File "/home/xinyuzhao/faultModel/src/playground/corrupt.py", line 87, in _tensor_inject
    orig_value = tensor[index].item()
IndexError: too many indices for tensor of dimension 4

real	4m7.142s
user	5m48.346s
sys	2m6.458s
